apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-clone
  namespace: twitter
  labels:
    app:  twitter-clone
spec:
  selector:
    matchLabels:
      app: twitter-clone
  replicas: 1
  template:
    metadata:
      labels:
        app:  twitter-clone
    spec:
      containers:
      - name:  twitter-clone
        image:  boluex/twitter_clone:1.3
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        
---
apiVersion: v1
kind: Service
metadata:
  name:  twitter-clone
  namespace: twitter
spec:
  selector:
    app:  twitter-clone
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
    nodePort: 30080
  


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  twitter-clone
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app:  twitter-clone
  namespaceSelector:
    matchNames:
    - twitter
  endpoints:
  - interval: 15s
    port: http
    path: /metrics
    scrapeTimeout: 14s

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: twitter-clone
  namespace: twitter
spec:
  rules:
  - host: twitter-clone.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: twitter-clone
            port:
              number: 80