# Generated by Django 3.2.9 on 2022-06-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_alter_posts_tagline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='follow_button',
        ),
    ]
